spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment} # 这里是把api去掉
            #           http://localhost:88/api/product/category/list/tree
            #           http://localhost:10000/product/category/list/tree
        - id: blog_route
          uri: lb://blog-manager
          predicates:
            - Path=/api/blog/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment} # 这里是把api去掉
            # http://localhost:88/api/product/category/list/tree
        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/** # 前端项目api
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment} # 这里是把api去掉
        - id: admin_route
          uri: lb://renren-fast # lb表示负载均衡
          predicates:
            - Path=/api/** # 前端项目api
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment} #这里是把api替换为renren-fast
#            - http://localhost:88/api/  captcha.jpg
#            - http://localhost:8080/  renren-fast/captcha.jpg
#            使用路径重写
# http://localhost:88/api/blog/blog/list?t=1600400237129&page=1&limit=10&key= 404 (Not Found)

