spring:
  cloud:
    gateway:
      routes:

        - id: product-service
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: mall-third-party-service
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty(?<segment>/?.*), /$\{segment}

        - id: mall-member
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: mall-ware
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: admin-manager
          uri: lb://renren-fast  # 负载均衡到  renren-fast 服务
          predicates:
            - Path=/api/**  # 前端项目 带上api前缀
          filters:
            - RewritePath=/api(?<segment>/?.*), /renren-fast$\{segment}

        - id: mall_host_route  # nginx 的 请求 到来，按照host 的 值来 配置
          uri: lb://mall-product
          predicates:
            - Host=fkmall.shop,item.fkmall.shop
