spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GAMWbzLyZYLJZPYVNKC
      secret-key: QAub0YkfqTLIxfD3LEjvJIiMLYChd6
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: fangkai-file
      sms:
        host: http://127.0.0.1:30000
        path: /sms/send
        appcode: f7841c7c1e664010a03b12090d0ec2f7
        template-id: M09DD535F4
  application:
    name: mall-third-party
server:
  port: 30000